/**
 * Lucide icons — subset เฉพาะที่แอปใช้ (แทนการโหลด lucide.min.js เต็มตัว 426KB
 * แบบ render-blocking ใน <head>) — tree-shake แล้วเข้า main bundle
 *
 * รายชื่อ = data-lucide literal ใน index.html + src/*.ts ทั้งหมด
 * บวกค่าที่ถูกกำหนดผ่านตัวแปร (dynamic) ใน app.ts:
 *   toast: info, check-circle-2 · pills: badge-check, sparkles · dashboard: layers, activity, star
 *   buildLinkField: link-2, facebook, globe · toggle password: eye-off
 *
 * หมายเหตุ: npm lucide 1.x ถอด brand icons ออกแล้ว — Facebook จึงนิยามเอง
 * ด้วย path เดิมของ lucide เพื่อคงหน้าตาเหมือนก่อนหน้า
 */
import { createIcons, type IconNode } from 'lucide';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart2,
  BarChart3,
  BadgeCheck,
  Briefcase,
  Building,
  Building2,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Copy,
  Crosshair,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileEdit,
  FileSpreadsheet,
  FileText,
  Globe,
  Hash,
  Image,
  ImageOff,
  ImagePlus,
  Info,
  Inbox,
  Layers,
  LayoutGrid,
  Link2,
  List,
  Loader2,
  LogIn,
  LogOut,
  MapPin,
  PackagePlus,
  PackageX,
  Pencil,
  Phone,
  PhoneCall,
  PieChart,
  PlusCircle,
  QrCode,
  RotateCcw,
  Save,
  Search,
  Sparkles,
  Star,
  Tags,
  Trash2,
  Upload,
  User,
  UserPlus,
  Users,
  X,
  ZoomIn,
} from 'lucide';

// โครงสร้างข้อมูลเดียวกับ IconNode ของ lucide: array ของ [tag, attrs]
const Facebook = [
  ['path', { d: 'M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z' }],
] as unknown as IconNode;

const subset = {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart2,
  BarChart3,
  BadgeCheck,
  Briefcase,
  Building,
  Building2,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Copy,
  Crosshair,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  FileEdit,
  FileSpreadsheet,
  FileText,
  Globe,
  Hash,
  Image,
  ImageOff,
  ImagePlus,
  Info,
  Inbox,
  Layers,
  LayoutGrid,
  Link2,
  List,
  Loader2,
  LogIn,
  LogOut,
  MapPin,
  PackagePlus,
  PackageX,
  Pencil,
  Phone,
  PhoneCall,
  PieChart,
  PlusCircle,
  QrCode,
  RotateCcw,
  Save,
  Search,
  Sparkles,
  Star,
  Tags,
  Trash2,
  Upload,
  User,
  UserPlus,
  Users,
  X,
  ZoomIn,
};

// legacy code เรียก window.lucide.createIcons() (app.ts / bootstrap.ts)
(window as unknown as { lucide: { createIcons: () => void; icons: typeof subset } }).lucide = {
  createIcons: () => createIcons({ icons: subset }),
  icons: subset,
};
